-- 1. TABLA DE CLIENTES / COMPRADORES
CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key TEXT NOT NULL, -- Identificador del emisor o usuario de la app
    id_cliente TEXT NOT NULL,
    nombre_razon_social TEXT NOT NULL,
    cif_nif TEXT,
    direccion TEXT,
    codigo_postal TEXT,
    poblacion TEXT,
    provincia TEXT,
    email TEXT,
    telefono TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uq_cliente_user UNIQUE (user_key, id_cliente)
);

-- 2. TABLA MAESTRA DE PRECIOS Y ARTÍCULOS
CREATE TABLE IF NOT EXISTS precios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key TEXT NOT NULL,
    codigo_articulo TEXT NOT NULL,
    coleccion TEXT,
    nombre_articulo TEXT NOT NULL,
    categoria TEXT,
    id_cliente TEXT, -- Puede vincularse a un cliente específico o ser general
    precio_cliente NUMERIC(10, 2) DEFAULT 0.00,
    precio_confeccion NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABLA ENCABEZADO DE FACTURAS (VENTAS)
CREATE TABLE IF NOT EXISTS facturas_encabezado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key TEXT NOT NULL,
    numero_factura TEXT NOT NULL,
    fecha_emision DATE NOT NULL,
    id_cliente TEXT NOT NULL,
    nombre_cliente TEXT,
    cif_cliente TEXT,
    base_imponible NUMERIC(10, 2) DEFAULT 0.00,
    porcentaje_iva NUMERIC(5, 2) DEFAULT 21.00,
    cuota_iva NUMERIC(10, 2) DEFAULT 0.00,
    total_factura NUMERIC(10, 2) DEFAULT 0.00,
    estado TEXT DEFAULT 'Cobrada', -- 'Pendiente', 'Cobrada', 'Anulada'
    ruta_archivo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uq_factura_user UNIQUE (user_key, numero_factura)
);

-- 4. TABLA DETALLADA DE LÍNEAS DE FACTURA (RELACIONADA CON FACTURAS)
CREATE TABLE IF NOT EXISTS facturas_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id BIGINT REFERENCES facturas_encabezado(id) ON DELETE CASCADE,
    numero_factura TEXT NOT NULL,
    codigo_articulo TEXT,
    descripcion TEXT NOT NULL,
    cantidad NUMERIC(10, 2) NOT NULL DEFAULT 1,
    precio_unitario NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TABLA DE GASTOS Y COMPRAS (MEJORA FUTURA)
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key TEXT NOT NULL,
    proveedor TEXT NOT NULL,
    cif_nif TEXT,
    concepto TEXT,
    categoria TEXT, -- 'Gasolina', 'Luz/Agua', 'Costureras', 'Materia Prima'
    fecha DATE NOT NULL,
    base_imponible NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    porcentaje_iva NUMERIC(5, 2) DEFAULT 21.00,
    cuota_iva NUMERIC(10, 2) DEFAULT 0.00,
    porcentaje_irpf NUMERIC(5, 2) DEFAULT 0.00,
    retencion_irpf NUMERIC(10, 2) DEFAULT 0.00,
    total_gasto NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    es_vehiculo BOOLEAN DEFAULT FALSE, -- Para aplicar regla del 50% de IVA
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);