[microsoft]
client_id = "cfb030ee-679e-43f8-8c69-48c1cfb47608"
tenant_id = "25e8c3f0-d741-4cfc-a768-81a0429c6a12"

[emisores]
arturo = { nombre_fiscal = "Arturo Castro García", cif = "03922281-E", direccion = "Calle Isidro del Río, 23", codigo_postal = "45121, Las Navillas (Toledo)", telefono = "645 84 44 62", mail = "patronajearturo@outlook.com", cuenta = "CaixaBank", numero_cuenta = "ES87 2100 1208 1201 0023 3210" }
carmen = { nombre_fiscal = "María Carmen García López", cif = "70330011-J", direccion = "Travesía Calera, 17", codigo_postal = "45120, San Pablo de los Montes (Toledo)", telefono = "675 81 13 57", mail = "", cuenta = "Santander", numero_cuenta = "ES41 0049 6385 3028 1000 8510" }